IsTakipProjesiMVC/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IsTakipProjesiMVC.Controllers
{
    public class LogoutController : Controller
    {
        // GET: Logout
        public ActionResult Index()
        {
            Session.Abandon();
            return RedirectToAction("Index","Login");
        }
    }
}

IsTakipProjesiMVC/Views/Shared/_LayoutCalisan.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>İş Takip Admin Çalışan</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>


</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand " href="#">İş Takip Çalışan</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        @Html.ActionLink("Anasayfa", "Index", "Calisan", new { }, new { @class = "nav-link" })
                    </li>

                    <li class="nav-item">
                        @Html.ActionLink("İş Tamamla", "Yap", "Calisan", new { }, new { @class = "nav-link" })
                    </li>

                    <li class="nav-item">
                        @Html.ActionLink("İş Takip", "Takip", "Calisan", new { }, new { @class = "nav-link" })
                    </li>


                </ul>
             


                <div class="d-flex nav-item">
                    @Html.ActionLink("Çıkış", "Index", "Logout", new { }, new { @class = "btn btn-danger" })
                </div>



            </div>
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>

IsTakipProjesiMVC/Views/Shared/_LayoutYönetici.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>İş Takip Admin Yönetici</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>


</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
          
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <a class="navbar-brand" href="#">İş Takip Yönetici</a>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        @Html.ActionLink("Anasayfa", "Index", "Yönetici", new { }, new { @class = "nav-link" })
                    </li>

                    <li class="nav-item">
                        @Html.ActionLink("İş Ata", "Ata", "Yönetici", new { }, new { @class = "nav-link" })
                    </li>

                    <li class="nav-item">
                        @Html.ActionLink("İş Takip", "Takip", "Yönetici", new { }, new { @class = "nav-link" })
                    </li>


                </ul>
                <div class="d-flex nav-item">
                    @Html.ActionLink("Çıkış", "Index", "Logout", new{}, new { @class="btn btn-danger"})
                </div>

            </div>
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>